name: DynapSEtorch
channels:
  - conda-forge
  - pytorch 
  - defaults
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.6
  - pip>=22.3
  - pip:
    - numpy
    - matplotlib
    - brian2
    - sympy==1.4
    - jupyter
    - jupyterlab
    - sphinx>=4.0
    - sphinx-book-theme
    - myst_nb
    - pbr
    - ipywidgets