[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ARCANA"
dynamic = ["version"]
requires-python = ">= 3.10"
authors = [
  {name = "Fernando M. Quintana", email = "f.m.quintana.velazquez@rug.nl"},
]
maintainers = [
  {name = "Fernando M. Quintana", email = "f.m.quintana.velazquez@rug.nl"}
]
description = "ARCANA neural model simulation on PyTorch."
license = {file = "LICENSE"}
readme = "README.md"

classifiers = [
    "Development Status :: 1 - Planning",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Programming Language :: Python :: 3.11",
    "Operating System :: OS Independent",
]
dependencies = [
  "torch",
  "numpy",
  "matplotlib",
  "seaborn",
  "tonic",
  "tensorboard",
  "boilerplot@git+https://github.com/fehlings/boilerplot.git",
]

[project.optional-dependencies]
dev = [
  "pre-commit",
  "black[jupyter]",
  "isort",
  "flake8-black",
  "flake8-isort",
  "sphinx>=4.0",
  "sphinx-book-theme",
  "myst_nb",
  "pytest"
]


[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.version]
path = "arcana/__init__.py"

[tool.hatch.build.targets.wheel]
include = [
  "arcana/",
]

[project.urls]
Homepage = "https://github.com/ferqui/ARCANA"
Documentation = "https://dynapsetorch.readthedocs.io/en/latest/"
Repository = "https://github.com/ferqui/ARCANA"
